[package]
name = "backend"
version = "0.1.0"
authors = ["Krzysztof HadaÅ› <krzysztofhadas6@gmail.com>"]

[dependencies]
actix-web = "0.7"
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"
serde = "1.0"
rand = "0.6.1"
serde_derive = "1.0"